---
- name: Install influxdb packages
  apt:
    name: "{{ influxdb_apt_package }}"
    state: present
    update_cache: yes

- name: Ensure {{ influxdb_service_name }} service started and start up at boot
  service:
    name: "{{ influxdb_service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes
