---
- include_tasks: influxdb_auth_remove.yml

- name: Create database
  influxdb_database:
    hostname: localhost
    database_name: "{{ item }}"
    state: present
  with_items: "{{ influxdb_databases }}"

- include_tasks: influxdb_auth_revert.yml