---
- name: Install influxdb packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ influxdb_apt_package }}"

- name: Ensure {{ influxdb_service_name }} service started and start up at boot
  service:
    name: "{{ influxdb_service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes