---
- name: Revert change auth-enabled
  ini_file:
    path: "{{ influxdb_config_file_path }}"
    section: http
    option: auth-enabled
    value: "true"
  when: 
    - influxdb_change_auth.changed
    - influxdb_config.http.auth_enabled
  notify: Restart influxdb

- name: Revert change https-enabled
  ini_file:
    path: "{{ influxdb_config_file_path }}"
    section: http
    option: https-enabled
    value: "true"
  when: 
    - influxdb_change_https.changed
    - influxdb_config.http.https_enabled
  notify: Restart influxdb

- meta: flush_handlers
