---
- include_tasks: influxdb_auth_remove.yml
  when: influxdb_config.http["https-enabled"] == true

- name: Create database
  influxdb_database:
    hostname: localhost
    database_name: "{{ item }}"
    state: present
  with_items: "{{ influxdb_databases }}"

- include_tasks: influxdb_auth_revert.yml
  when: influxdb_config.http["https-enabled"] == true