---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- include_tasks: influxdb_pre.yml
- include_tasks: influxdb_install.yml

- block: # Config InfluxDB
  - include_tasks: influxdb_search_config.yml
  - include_tasks: influxdb_post.yml
  tags:
    - influxdb-config
    - influxdb-drop-config

- include_tasks: influxdb_database.yml
  tags:
    - influxdb-config
    - influxdb-database

- include_tasks: influxdb_credential.yml
  tags:
    - influxdb-config
    - influxdb-user